version: "3.9"

services:
  virtual-wallet:
    image: mariadb:11
    container_name: virtual-wallet-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: virtual_wallet
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mariadb-admin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: .
    container_name: virtual-wallet-backend
    depends_on:
      virtual-wallet:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://virtual-wallet:3306/virtual_wallet
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

volumes:
  db_data: